mkdir $1
touch "$1/a-out"
touch "$1/a.cpp"
touch "$1/b.cpp"
touch "$1/c.cpp"
touch "$1/d.cpp"
touch "$1/e.cpp"
cd "$1"
str1="#include <iostream>"
str2="#include <string>"
str3="#include <vector>"
str4="#include <algorithm>"
str5="using namespace std;"
str6="int main(int argc, char const *argv[]) {\n"
str7="\t     return 0;"
str8="}"
for file in *.cpp; do
  echo -e $str1 >> "$file"
  echo -e $str2 >> "$file"
  echo -e $str3 >> "$file"
  echo -e $str4 >> "$file"
  echo -e $str5 >> "$file"
  echo -e $str6 >> "$file"
  echo -e $str7 >> "$file"
  echo -e $str8 >> "$file"
done
