mkdir $1
touch "$1/comments.txt"
touch "$1/a-out"
touch "$1/f.cpp"
touch "$1/g.cpp"
touch "$1/h.cpp"
touch "$1/i.cpp"
touch "$1/j.cpp"
cd "$1"
str1="#include <iostream>"
str2="#include <string>"
str3="#include <vector>"
str4="#include <algorithm>"
str5="using namespace std;"
str6="int main(int argc, char const *argv[]) {\n"
str7="\treturn 0;"
str8="}"
for file in *.cpp; do
  echo -e $str1 >> "$file"
  echo -e $str2 >> "$file"
  echo -e $str3 >> "$file"
  echo -e $str4 >> "$file"
  echo -e $str5 >> "$file"
  echo -e $str6 >> "$file"
  echo -e $str7 >> "$file"
  echo -e $str8 >> "$file"
done
